version: "3.0"

services:
  workspace:
    image: python:3.9
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - 'PS1=[\u@\h \W] \$$ '
      - LW_API_BOT_ID
      - LW_API_BOT_SECRET
      - LW_API_CLIENT_ID
      - LW_API_CLIENT_SECRET
      - LW_API_SERVICE_ACCOUNT
      - LW_API_PRIVATEKEY
    command: /bin/bash -c "bash"
