version: "3.0"

services:
  workspace:
    image: eclipse-temurin:17
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - 'PS1=[\u@\h \W] \$$ '
    command: /bin/bash -c "bash"
